//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_4.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        public Cours()
        {
            this.Courses1 = new HashSet<Cours>();
            this.CouseStudents = new HashSet<CouseStudent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int PreReq { get; set; }
    
        public virtual ICollection<Cours> Courses1 { get; set; }
        public virtual Cours Cours1 { get; set; }
        public virtual ICollection<CouseStudent> CouseStudents { get; set; }
    }
}
