//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_4.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.CouseStudents = new HashSet<CouseStudent>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public double Cgpa { get; set; }
    
        public virtual ICollection<CouseStudent> CouseStudents { get; set; }
    }
}
